// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonLogout: typeof import('~icons/carbon/logout')['default']
    CarbonUserAvatarFilled: typeof import('~icons/carbon/user-avatar-filled')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    LayoutHeader: typeof import('./components/LayoutHeader.vue')['default']
    LayoutLeftMenu: typeof import('./components/LayoutLeftMenu.vue')['default']
    Logo: typeof import('./components/logo.vue')['default']
    PageTemplate: typeof import('./components/PageTemplate.vue')['default']
    README: typeof import('./components/README.md')['default']
    UserOut: typeof import('./components/UserOut.vue')['default']
  }
}

export { }
