// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Announcement: typeof import('./components/Announcement.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonLogout: typeof import('~icons/carbon/logout')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonUserAvatarFilled: typeof import('~icons/carbon/user-avatar-filled')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    LayoutHeader: typeof import('./components/LayoutHeader.vue')['default']
    LayoutLeftMenu: typeof import('./components/LayoutLeftMenu.vue')['default']
    Logo: typeof import('./components/logo.vue')['default']
    PageTemplate: typeof import('./components/PageTemplate.vue')['default']
    README: typeof import('./components/README.md')['default']
    UserOut: typeof import('./components/UserOut.vue')['default']
  }
}

export { }
